name: delta_to_html
version: 0.1.2

description: A library for converting Delta To HTML  of the package flutter_quill.
homepage: https://github.com/secanonm/DeltaToHTML

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.1
  charcode: ^1.3.1
  collection: ^1.16.0
  flutter_quill: ^5.0.4
  markdown: ^5.0.0  
  
dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  test: ^1.21.1
